name: C_C++_CI

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - master

jobs:
  Build-and-test:
    uses: TLW-orgtesting/ci-config/.github/workflows/c-cpp_tmpl.yml@main
    with: 
      get_dependencies_params: 'gcc gcovr cmake'
