name: C_C++_CI

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - master

jobs:
  Build-Documentation:
    uses: TLW-orgtesting/ci-config/.github/workflows/c-cpp_tmpl.yml@main
    with: 
      reponame_cxx_api: 'gcc gcovr cmake'
