name: Build and Deploy Documentation
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Build-Documentation:
    uses: TLW-orgtesting/ci-config/.github/workflows/deploy_docs_tmpl.yml@main
    with: 
      reponame_cxx_api: utilities_cxx_api
      dependencies: cmake doxygen sphinx
