name: Test Documentation
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  build-documentation:
    uses: TLW-orgtesting/ci-config/.github/workflows/test_docs_tmpl_2.yml@main
    with:
      repoName: utilities_cxx_api
